apiVersion: v1
kind: ConfigMap
metadata:
  name: guardrails-orchestrator-config
data:
  regexDetectorImage: 'na.artifactory.swg-devops.com/sys-linux-power-team-ftp3distro-docker-images-docker-local/regex-detector:latest'
  vllmGatewayImage: 'na.artifactory.swg-devops.com/sys-linux-power-team-ftp3distro-docker-images-docker-local/vllm-orchestrator-gateway:latest'
