apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/accelerator-name: ""
    opendatahub.io/apiProtocol: REST
    opendatahub.io/hardware-profile-name: small-serving-1bmle
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/template-display-name: Hugging Face Detector ServingRuntime for KServe (ppc64le)
    opendatahub.io/template-name: guardrails-detector-huggingface-runtime
    openshift.io/display-name: guardrails-detector-ibm-hap
  labels:
    opendatahub.io/dashboard: "true"
  name: guardrails-detector-ibm-hap
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
  - args:
    - --workers=1
    - --host=0.0.0.0
    - --port=8000
    - --log-config=/common/log_conf.yaml
    command:
    - uvicorn
    - app:app
    env:
    - name: MODEL_DIR
      value: /mnt/models
    - name: HF_HOME
      value: /tmp/hf_home
    image: quay.io/vahirwad/trustyai-hf-detector:latest
    name: kserve-container
    ports:
    - containerPort: 8000
      protocol: TCP
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: guardrails-detector-hf-runtime
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 2Gi
    name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: guardrails-detector-ibm-hap
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"
  name: guardrails-detector-ibm-hap
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: guardrails-detector-hf-runtime
      name: ""
      resources:
        limits:
          cpu: "8"
          memory: 10Gi
        requests:
          cpu: "4"
          memory: 8Gi
      runtime: guardrails-detector-ibm-hap
      storage:
        key: s3-creds
        path: models/granite-guardian-hap-125m
